[colors.bright]
black = "0x727072"
blue = "0xFC9867"
cyan = "0x78DCE8"
green = "0xA9DC76"
magenta = "0xAB9DF2"
red = "0xFF6188"
white = "0xFCFCFA"
yellow = "0xFFD866"

[colors.normal]
black = "0x403E41"
blue = "0xFC9867"
cyan = "0x78DCE8"
green = "0xA9DC76"
magenta = "0xAB9DF2"
red = "0xFF6188"
white = "0xFCFCFA"
yellow = "0xFFD866"

[colors.primary]
background = "0x2D2A2E"
foreground = "0xFCFCFA"

[font]
normal = { family = "UbuntuMono Nerd Font Mono" }
size = 16

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B\u0001"
key = "A"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0002"
key = "B"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0003"
key = "C"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0004"
key = "D"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0005"
key = "E"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0006"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0007"
key = "G"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0008"
key = "H"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0009"
key = "I"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u000A"
key = "J"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u000B"
key = "K"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u000C"
key = "L"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u000D"
key = "M"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u000E"
key = "N"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u000F"
key = "O"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0010"
key = "P"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0011"
key = "Q"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0012"
key = "R"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0013"
key = "S"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0014"
key = "T"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0015"
key = "U"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0016"
key = "V"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0017"
key = "W"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0018"
key = "X"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u0019"
key = "Y"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B\u001A"
key = "Z"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B`"
key = "`"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B~"
key = "`"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B*"
key = "Key8"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B#"
key = "Key3"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B>"
key = ">"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B<"
key = "<"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B_"
key = "Minus"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B%"
key = "Key5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B^"
key = "Key6"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B\\"
key = "Backslash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B|"
key = "Backslash"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B;"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

# [schemes.afterglow.bright]
# black = "0x636363"
# blue = "0x7eaac7"
# cyan = "0x86d3ce"
# green = "0x909d63"
# magenta = "0xaa6292"
# red = "0xbc5653"
# white = "0xf7f7f7"
# yellow = "0xebc17a"

# [schemes.afterglow.cursor]
# cursor = "0xd9d9d9"
# text = "0x2c2c2c"

# [schemes.afterglow.dim]
# black = "0x232323"
# blue = "0x556b79"
# cyan = "0x5c8482"
# green = "0x5e6547"
# magenta = "0x6e4962"
# red = "0x74423f"
# white = "0x828282"
# yellow = "0x8b7653"

# [schemes.afterglow.normal]
# black = "0x1c1c1c"
# blue = "0x7eaac7"
# cyan = "0x86d3ce"
# green = "0x909d63"
# magenta = "0xaa6292"
# red = "0xbc5653"
# white = "0xcacaca"
# yellow = "0xebc17a"

# [schemes.afterglow.primary]
# background = "0x2c2c2c"
# bright_background = "0x3a3a3a"
# bright_foreground = "0xd9d9d9"
# dim_background = "0x202020"
# dim_foreground = "0xdbdbdb"
# foreground = "0xd6d6d6"

# [schemes.monokai_pro.bright]
# black = "0x727072"
# blue = "0xFC9867"
# cyan = "0x78DCE8"
# green = "0xA9DC76"
# magenta = "0xAB9DF2"
# red = "0xFF6188"
# white = "0xFCFCFA"
# yellow = "0xFFD866"

# [schemes.monokai_pro.normal]
# black = "0x403E41"
# blue = "0xFC9867"
# cyan = "0x78DCE8"
# green = "0xA9DC76"
# magenta = "0xAB9DF2"
# red = "0xFF6188"
# white = "0xFCFCFA"
# yellow = "0xFFD866"

# [schemes.monokai_pro.primary]
# background = "0x2D2A2E"
# foreground = "0xFCFCFA"

# [schemes.zenburn.normal]
# black = "0x3f3f3f"
# blue = "0x8cd0d3"
# cyan = "0x93e0e3"
# green = "0x7f9f7f"
# magenta = "0xdc8cc3"
# red = "0xcc9393"
# white = "0xdcdccc"
# yellow = "0xf0dfaf"

# [schemes.zenburn.primary]
# background = "0x3f3f3f"
# foreground = "0xdcdccc"

[scrolling]
history = 0

[window]
decorations = "none"
startup_mode = "Maximized"
title = "Terminal (Alacritty)"

[cursor]
blink_interval = 750

[cursor.style]
blinking = "Always"

